version: '3.8'
services:
  postgres:
    image: postgres:18
    container_name: ploutos-postgres
    environment:
      POSTGRES_USER: ploutos
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ploutos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: